### ISSUE TITLE
`LLMChain.run()` for ollama doesn't work

### ISSUE THREAD

**Issue by petrkozorezov** [brainlid/langchain#71]
```elixir
alias LangChain.{Chains.LLMChain, Message, LangChain.ChatModels.ChatOllamaAI}
LLMChain.new!(%{
  llm: LangChain.ChatModels.ChatOllamaAI.new!(%{
    model: "mixtral:8x7b-instruct-v0.1-q4_K_M"
  }),
  verbose: true,
})
|> LLMChain.add_message(Message.new_user!("hello world!"))
|> LLMChain.run()
```

```
** (CaseClauseError) no case clause matching: {:ok, %LangChain.Message{content: " Hello! It's nice to see you. Is there something specific you would like to talk about or ask me a question? I'm here to help with any programming-related questions you have.\n\nIf you don't have anything specific in mind, that's okay too! We can just chat about whatever interests you. Do you enjoy coding? What are some of your favorite programming languages and why do you like them?\n\nI'm particularly fond of Python, because it's a great language for beginners to learn, with a clean and easy-to-understand syntax. It's also very versatile and can be used for a wide variety of applications, from web development to data analysis to machine learning.\n\nBut enough about me! I want to hear about you. What brings you to coding? Is there something specific you're hoping to learn or accomplish with your programming skills? Let me know and I'll do my best to help you out.", index: nil, status: :complete, role: :assistant, function_name: nil, arguments: nil}}
    (langchain 0.1.7) lib/chains/llm_chain.ex:209: LangChain.Chains.LLMChain.do_run/1
    (langchain 0.1.7) lib/chains/llm_chain.ex:170: LangChain.Chains.LLMChain.run/2
    iex:4: (file)
```

**Comment by brainlid** [comment]
Ah, that must be from the main branch.

@medoror, can you please help diagnose and verify this?

**Comment by medoror** [comment]
yea I think I noticed this. Will report back later today on my findings

**Comment by petrkozorezov** [comment]
I think the problem is [here](https://github.com/brainlid/langchain/blob/ba2b8d3db7e46b805279c158b200759f0bda7401/lib/chains/llm_chain.ex#L203). This case doesn't handle case `{:ok, message}`, but according to [spec](https://github.com/brainlid/langchain/blob/ba2b8d3db7e46b805279c158b200759f0bda7401/lib/chat_models/chat_model.ex#L8) it's possible.

**Comment by medoror** [comment]
@brainlid pushed a fix for this and validated that `LLMChain.run()`works for the given scenario. There might be some deeper thinking on the types though. Currently it doesn't account for the message deltas that are also returned by the call function

**Comment by brainlid** [comment]
Thanks @medoror! I merged it. Yes, I think some more thought will help but for now, your solution is a good fix.
